import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import worker from '../dist/server/index.js';import {scoreDatabase} from './preview-scores-db.mjs';
const DB=scoreDatabase(path.resolve('.sites-runtime/preview-scores.sqlite'));
const root=path.resolve('dist/client'),bucketRoot=path.resolve('.sites-runtime/preview-bucket');await fs.mkdir(bucketRoot,{recursive:true});const fileFor=key=>path.join(bucketRoot,Buffer.from(key).toString('base64url'));
const BUCKET={async list({prefix}){return {objects:(await fs.readdir(bucketRoot)).map(name=>Buffer.from(name,'base64url').toString()).filter(key=>key.startsWith(prefix)).map(key=>({key})),truncated:false}},async get(key){try{const data=await fs.readFile(fileFor(key));return {body:data,json:async()=>JSON.parse(data.toString())}}catch(e){if(e.code==='ENOENT')return null;throw e}},async put(key,value){await fs.writeFile(fileFor(key),typeof value==='string'?Buffer.from(value):Buffer.from(await new Response(value).arrayBuffer()))},async delete(key){await fs.rm(fileFor(key),{force:true})}};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.mp3':'audio/mpeg','.wav':'audio/wav','.jpg':'image/jpeg','.png':'image/png'};
const ASSETS={async fetch(request){const pathname=new URL(request.url).pathname,file=path.resolve(root,'.'+decodeURIComponent(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep))return new Response('Not found',{status:404});try{return new Response(await fs.readFile(file),{headers:{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'}})}catch{return new Response('Not found',{status:404})}}};
const qa=`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:12px;background:#252532;color:#fff;font:16px Arial}button{padding:8px;margin:0 6px 6px 0}iframe{display:block;border:1px solid #777;background:#000}</style><h1 style="font-size:18px;margin:4px 0 8px">手機尺寸操作驗證</h1><button onclick="size(390,844)">390 × 844</button><button onclick="size(320,568)">320 × 568</button><button onclick="size(844,390)">844 × 390 橫向</button><button onclick="document.querySelector('iframe').contentWindow.location.reload()">重新開啟遊戲</button><p id="size">390 × 844</p><iframe title="手機尺寸 BeatStream" src="/" width="390" height="844"></iframe><script>function size(w,h){const f=document.querySelector('iframe');f.width=w;f.height=h;document.querySelector('#size').textContent=w+' × '+h}</script></html>`;
const args=process.argv.slice(2),port=Number(args[args.indexOf('--port')+1])||4173;
http.createServer(async(req,res)=>{try{const origin='http://'+req.headers.host,url=origin+req.url;if(req.url==='/__qa'){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(qa);return}const headers=new Headers(req.headers);headers.set('oai-authenticated-user-id','preview-owner');const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:req,duplex:'half'}:{})});const response=await worker.fetch(request,{BUCKET,DB,ASSETS});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(e){console.error(e);res.writeHead(500);res.end('Preview error')}}).listen(port,'0.0.0.0',()=>console.log('BeatStream preview listening on '+port));
